In [1]:
from google.colab import files
uploaded = files.upload()

Saving train (7).csv to train (7).csv

In [3]:
import pandas as pd

df = pd.read_csv("train (7).csv")
df

      battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0               842     0          2.2  ...             0     1            1
1              1021     1          0.5  ...             1     0            2
2               563     1          0.5  ...             1     0            2
3               615     1          2.5  ...             0     0            2
4              1821     1          1.2  ...             1     0            1
...             ...   ...          ...  ...           ...   ...          ...
1995            794     1          0.5  ...             1     0            0
1996           1965     1          2.6  ...             1     1            2
1997           1911     0          0.9  ...             1     0            3
1998           1512     0          0.9  ...             1     1            0
1999            510     1          2.0  ...             1     1            3

[2000 rows x 21 columns]

In [4]:
df.isna().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [5]:
X = df.drop(['price_range'], axis = 1)
y = df['price_range']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=1/3, random_state=42)

svm:

In [6]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.svm import SVC
model=SVC()
cvs0 = cross_val_score(estimator=model, X=X, y=y, cv=6, scoring='accuracy')
print("accuracy")
print(cvs0.mean())

accuracy
0.9524929120737503

нейронка

In [28]:
X = df.iloc[:,0:12]  # y = ax [диапазон строк, диапазон столбцов]
Y = df.iloc[:,20] 
X

      battery_power  blue  clock_speed  ...  n_cores  pc  px_height
0               842     0          2.2  ...        2   2         20
1              1021     1          0.5  ...        3   6        905
2               563     1          0.5  ...        5   6       1263
3               615     1          2.5  ...        6   9       1216
4              1821     1          1.2  ...        2  14       1208
...             ...   ...          ...  ...      ...  ..        ...
1995            794     1          0.5  ...        6  14       1222
1996           1965     1          2.6  ...        4   3        915
1997           1911     0          0.9  ...        8   3        868
1998           1512     0          0.9  ...        5   5        336
1999            510     1          2.0  ...        6  16        483

[2000 rows x 12 columns]

In [36]:
from keras.models import Sequential
from keras.layers import Dense
import numpy
#
model = Sequential()
#Входной слой с 12ю признаками, потом 4 скрытых слоя, потом выходной слой
model.add(Dense(12, input_dim=12, activation='relu'))

model.add(Dense(10, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(3, activation='relu'))

model.add(Dense(1, activation='softmax'))

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=['accuracy', 'Recall'])
model.fit(X, Y, epochs = 15)

Epoch 1/15
63/63 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2528 - recall: 1.0000
Epoch 2/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2496 - recall: 1.0000
Epoch 3/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2358 - recall: 1.0000
Epoch 4/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2656 - recall: 1.0000
Epoch 5/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2703 - recall: 1.0000
Epoch 6/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2388 - recall: 1.0000
Epoch 7/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2482 - recall: 1.0000
Epoch 8/15
63/63 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2464 - recall: 1.0000
Epoch 9/15
63/63 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2369 - recall: 1.0000
Epoch 10/15
63/63 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2556 - recall: 1.0000
Epoch 11/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2508 - recall: 1.0000
Epoch 12/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2354 - recall: 1.0000
Epoch 13/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2589 - recall: 1.0000
Epoch 14/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2426 - recall: 1.0000
Epoch 15/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2508 - recall: 1.0000

In [41]:
from keras.models import Sequential
from keras.layers import Dense
import numpy
#
model = Sequential()
#Входной слой с 12ю признаками, потом 4 скрытых слоя, потом выходной слой
model.add(Dense(12, input_dim=12, activation='tanh'))

model.add(Dense(10, activation='tanh'))
model.add(Dense(8, activation='tanh'))
model.add(Dense(5, activation='tanh'))
model.add(Dense(3, activation='tanh'))

model.add(Dense(1, activation='softmax'))

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=['accuracy', 'Recall'])
model.fit(X, Y, epochs = 15)

Epoch 1/15
63/63 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2366 - recall: 1.0000
Epoch 2/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2384 - recall: 1.0000
Epoch 3/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2574 - recall: 1.0000
Epoch 4/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2615 - recall: 1.0000
Epoch 5/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2526 - recall: 1.0000
Epoch 6/15
63/63 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2625 - recall: 1.0000
Epoch 7/15
63/63 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2413 - recall: 1.0000
Epoch 8/15
63/63 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2416 - recall: 1.0000
Epoch 9/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2404 - recall: 1.0000
Epoch 10/15
63/63 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2563 - recall: 1.0000
Epoch 11/15
63/63 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2360 - recall: 1.0000
Epoch 12/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2444 - recall: 1.0000
Epoch 13/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2535 - recall: 1.0000
Epoch 14/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2495 - recall: 1.0000
Epoch 15/15
63/63 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2382 - recall: 1.0000

Видно, что всем известный и проверенный временем метод опорных векторов тут справляется намного лучше чем моя самодельная нейронка, с ненастроенными гиперпараметрами. Accuracy svm = 0.95, моей нейронки в среднем 0.25, я попробовал поменять функцию активации но это ничего не изменило. С ансамблями я пока не разобрался